---
title: "EDA in R"
subtitle: "Easier UI for me"
author: "Dylan Bay"
date: today
format:
  html:
    toc: true
    df-print: paged
editor: visual
---

```{r}
#| label: setup
#| include: false

library(conflicted)

# Core
library(tidyverse)
library(vroom)
library(janitor)
library(DBI)
library(RSQLite)
library(here)
library(readxl)

# Modeling and EDA
library(car)
library(skimr)
library(naniar)

# Visuals and Formatting
library(broom)
library(patchwork)
library(scales)
library(glue)
library(cowplot)

# Package Conflicts
conflicts_prefer(
  dplyr::filter, dplyr::lag, dplyr::select, janitor::chisq.test, janitor::fisher.test, purrr::some, 
  purrr::discard, readr::col_factor, lubridate::here, dplyr::recode, purrr::some, skimr::n_complete,
  vroom::col_factor, patchwork::align_plots, lubridate::stamp
)
conflict_prefer_all("vroom", losers = "readr")  # These two overlap pretty directly
# Comment out library(conflicted) to see exact conflicts and masking happening by default

# Options
knitr::opts_chunk$set(  
  fig.width = 8,
  fig.height = 5,
  fig.align = "center",
  dpi = 300
) # beyond YAML defaults
options(scipen = 999)
options(theme_set(theme_cowplot()))
```

# Introduction

I will be analyzing THIS data source. For some background, CONTEXT. The goal is to OBJECTIVE.

# Import

```{r}
#| label: load-data

# GSHEETS DATA QUALITY ANALYSIS AND NOTES
df <- read_xlsx(here::here("data", "2026-04-21-gsheets.xlsx"),
                 skip = 15, col_types = c("date", "date", rep("guess", 5))) |> 
  slice(1:(n()-1)) |>  # one stupid header repeat at bottom
  slice(which(TYPE == "next"):n())  # include the next game(s) but no future slots
  # slice(which.max(TO <= today()):n())  # do not include any next games or future slots
# may also need to chop off a "next" game with "-" as NAME, I think is filler for double-nexts?

# Make sure to skip the first few rows, but also after grabbing column names...
#  the next few might have different numbers of rows! Depending on if "next" is a double, etc.
# NAME / NOTES column will need renaming
# unusual behavior: row 44, Trine Classic Collection; the 4 actual games are in the NAME/NOTES field
# others like this: Batman Arkham - Trilogy, Lego Batman Trilogy, Darksider's Fury Collection, Borderlands: The Handsome Collection, Shadowrun Collection, Tomb Raider Trilogy, BioShock: The Collection, Fallout® Classic Collection (twice!), LOVE, LISA: Definitive Edition, 
# "The Sims 4 - The Daring Lifestyle Bundle" puts a "-" in TYPE for some reason; also is like the above with 3 things in the notes column; ditto Destiny 2: Legacy Collection; maybe because these are "pack"
# contrarily e.g. "Idle Champions of the Forgotten Realms - Epic Champions of Renown Pack" will have the specific one called out after the - instead
# there are some cases where both a PC AND a mobile version are given away
#  example rows 28, 29 are mobile Botany Manor and PC Botany manor (NA TYPE)
#  but careful, not always reliable to have one be "mobile": rows 95 and 96 have Eastern Exorcist with one labeled dupe3 ("mobile dupe games")
# above implies we might want to split the TYPE field into 2 different fields to avoid overlap
# small handful of "Requires base game (payable/free)" pattern in notes, could be interesting
# Yes, Sludge Life free for 365 is technically not an error; consider drop as outlier? It was an epic exclusive
# "Hitman" shows as "free" type; but this is actually the WOA starter pack, NOT Hitman 1 or WOA itself
# yellow AND 'other' is indicative of a special event, off-cycle, weird-time or similarly weird but full game
# DEATH STRANDING - DIRECTORS CUT is listed as yellow other 0 day; this was an accidental listing live for a few hours, might need special treatment?
# A handful of titles have emoji or other characters in their names: the R trademark thing in Fallout and ohters, "Tormentor❌Punisher", a TM symbol for Apex Legends and others, a few m dashes, quote marks, U with hat in ABZU, a +, RAWMEN: Food Fighter Arena 🍜, parentheses, dots, 	>observer_, 
# A MNESIA special experience thing may be misspelled with extra space?
# Cat Quest 2 is marked as a dupe of Cat Quest II (similar III-type issues may exist elsewhere too)
# AND, of course, the whole thing about needing to down-propogate dates, weekday, days, NOT type though. Or up-propogate depending on sort! GSheets goes from recent to past.

# info contained in the header dropped rows:
#  dupe = dupe games, packs, ingame content, DLC
#  free = free games (permanently?)
#  other = 'other unique games' 'not the crappy free indie games'
#  pack2 = 'other' dupe games, packs, ingame content, DLC
#  dupe2 = 'other' dupe games, packs, ingame content, DLC
#  mobile = mobile unique games
#  pack3 = mobile packs, ingame content, DLC
#  dupe3 = mobile dupe games, packs, ingame content, DLC
#  next = next gifts ()
# cyan = normal game
# green = mystery game
# yellow = "not the usual gifts"
# light red = mobile 
# the version i'm looking at doesn't have the color-code data; what gives? Thought I fixed that

head(df)
tail(df)
unique(c(df$`NAME / NOTES`, df$DAYS, df$TYPE))
# df_g_og <- read_xlsx(here("data", "2026-04-21-gsheets.xlsx"))  # og for reference
# df_csv <- vroom(here("data", "2026-04-21-gsheets.csv"))  # no different, weird
```

```{r}
# WIKI DATA QUALITY ANALYSIS
dfw <- vroom(here("data", "2026-04-21-wiki.csv"))  # (w) for wiki version, vs (g) google sheets above
# instant notes here: well it's sorted the other way for one
# some russian leaks and even changes order, e.g. some of the idle champions, sims 4, Destiny 2, dark and darker, Rumbleverse, behind the frame i think is it
# capitalization can be different, Abzu (with hat thing) is partly lower case here, might impact matching, SUPERHOT (g) too as ex
# at least one is definitely missing: [REDACTED], >observer_, 
# Black Book didn't translate AT ALL and even has the weird doubleangle quote brackets
# some simply styled or filled in different: 3 out of 10 Episode 1 3 out of 10: Season Two (w) VS 3 out of 10, EP 1: "Welcome To Shovelworks", 3 out of 10: Season Two (g)
# for sure none of the mobile games are included as entries, port or no
# Even alphabetization cannot be trusted: Civilization VI (w) vs (g) Sid Meier's...
# a possible solution to sidestep this is to parse the date-ranges
#  would have to be start date since 1-day has no range; otherwise consistent in D-Month-YYYY
# newlines are destroyed for multi-entries, e.g. BioShock: The Collection BioShock Remastered BioS.., might need a fix on the scraper level with custom separator?
# dupe behavior is unpredictable; e.g. Alien Isolation only appears once in (w), the one-day, not the weeklong later
#  however both of A Plague Tale: Innocence are there despite also being a weeklong once and a oneday once??
# missing some events, like Saints Row: III (8-day!)
# strange error: data-sort-value="Evil Within, The 2"| The Evil Within 2 (w) here for some reason, parse error?

dfww <- vroom(here("data", "2026-04-21-wiki-enriched.csv"))
```

```{r}
only_g <- anti_join(df, dfw, by = c("NAME" = "Title")) %>% 
  mutate(source = "g, not w")
# dupes, packs, mobiles - but need to fill in NAs to be sure if that's it!

# 2. Find what is ONLY in set2
only_w <- anti_join(dfw, df, by = c("Title" = "NAME")) %>% 
  mutate(source = "W, NOT G")

# 3. Combine them to investigate all mismatches in one place
mismatches <- bind_rows(only_g, only_w)

# as mentioned before capitalization issues
# Alan Wake's American Nightmare doesn't match due to, of all things, straight vs curved apostrophe...
# expected but Anodyne 2 (w) vs Anodyne 2: Return to Dust (g)
# silly stuff like Astrea: Six Sided Oracles (g) vs Astrea: Six Sided Oracles (w) with hyphen vs space
# didn't see any but possible whitespace issues
# anyways there are lots of other mismatch reasons that I mostly covered above, like the bundling issue
# will need to revisit this once I've handled and cleaned some of the concepts already mentioned
# dunno if I can QUITE use a similarity score? wonder how hard the logic might be. 
# is it safe to just do an inner join, then apply special matching to JUST the mismatches, or is that error prone?
```


# EDA

Here is some initial descriptive information about our dataset.

```{r}
#| label: eda

# skim(df)
# df |> group_by(cat_var) |> skim()  # summaries per major category
# df |> skim() |> filter(n_missing > 0)  # summary of missings
# vis_miss(df)  # heatmap of missingness overall
# gg_miss_var(df)  # bar of missingness
# gg_miss_upset(df)  # easy col-to-col missingness associations
```

# Analysis

We will now proceed with our analysis.

```{r}
#| label: modeling

set.seed(1001)
```

# Conclusion

It is clear that FINDING. We recommend ACTION. Possible next steps include EXTRAS.
